contact_links:
  - name: Milkdown repository
    url: https://github.com/Saul-Mirone/milkdown
    about: For feature requests and/or issues related to the editor itself, please refer to the Milkdown repository
